openapi: 3.0.0
info:
  title: flask-restful-api-task
  version: 1.0.0
servers:
  - url: http://{{base_url}}articles
tags:
  - name: Articles
  - name: Comments
paths:
  /:
    get:
      tags:
        - Articles
      summary: list
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Articles
      summary: add
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                title: Test Title
                content: This is content of this Article
                author: rajat
                publication_date: '2024-06-20'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /9:
    put:
      tags:
        - Articles
      summary: update
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                title: Test Title
                content: This is content of this Article
                author: rajat
                publication_date: '2024-06-20'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /1:
    delete:
      tags:
        - Articles
      summary: delete
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Articles
      summary: detail
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /1/comments:
    post:
      tags:
        - Comments
      summary: add-comment
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                author: rajat
                content: Test Comment
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
